export declare const VERSION: string;
export declare const ON: SplitIO.Treatment;
export declare const OFF: SplitIO.Treatment;
export declare const CONTROL: SplitIO.Treatment;
export declare const CONTROL_WITH_CONFIG: SplitIO.TreatmentWithConfig;
export declare const getControlTreatmentsWithConfig: (featureFlagNames: unknown) => SplitIO.TreatmentsWithConfig;
export declare const WARN_SF_CONFIG_AND_FACTORY: string;
export declare const ERROR_SF_NO_CONFIG_AND_FACTORY: string;
export declare const ERROR_SC_NO_FACTORY: string;
export declare const WARN_ST_NO_CLIENT: string;
export declare const EXCEPTION_NO_REACT_OR_CREATECONTEXT: string;
export declare const WARN_NAMES_AND_FLAGSETS: string;
