export declare const VERSION: string;
export declare const ON: SplitIO.Treatment;
export declare const OFF: SplitIO.Treatment;
export declare const CONTROL: SplitIO.Treatment;
export declare const CONTROL_WITH_CONFIG: SplitIO.TreatmentWithConfig;
export declare const getControlTreatmentsWithConfig: (splitNames: unknown) => SplitIO.TreatmentsWithConfig;
export declare const WARN_SF_CONFIG_AND_FACTORY: string;
export declare const ERROR_SF_NO_CONFIG_AND_FACTORY: string;
export declare const ERROR_SC_NO_FACTORY: string;
export declare const WARN_ST_NO_CLIENT: string;
export declare const ERROR_UC_NO_USECONTEXT: string;
export declare const ERROR_UM_NO_USECONTEXT: string;
export declare const ERROR_UT_NO_USECONTEXT: string;
export declare const ERROR_UTRACK_NO_USECONTEXT: string;
export declare const EXCEPTION_NO_CREATECONTEXT: string;
